export const FETCH_ALL_COINS = "FETCH_ALL_COINS"
export const FETCH_COIN_DETAIL = "FETCH_COIN_DETAIL"
export const LOADING_ALL_COINS = "LOADING_ALL_COINS"
export const LOADING_COIN_DETAIL = "LOADING_COIN_DETAIL"
